# Required dim version
DIM_MIN_VERSION=1

# drm-tip configuration
#
# sourced as a bash script from dim

#
# drm-tip <repo> to <url list> associative array (declared in dim)
#
# <repo> (the key) is a symbolic name used for drm_tip_config, must match
# [a-z-]+
#
# <url list> (the value) is a space separated list of accepted URLs in order of
# preference
#
# dim users may freely choose the remote names and URLs from this list.
#
drm_tip_repos[drm-tip]="
ssh://git@ssh.gitlab.freedesktop.org/drm/tip.git
https://gitlab.freedesktop.org/drm/tip.git
"
drm_old_urls[drm-tip]="
git@gitlab.freedesktop.org:drm/tip.git
ssh://git@gitlab.freedesktop.org/drm/tip.git
ssh://git.freedesktop.org/git/drm/drm-tip
ssh://git.freedesktop.org/git/drm-tip
git://anongit.freedesktop.org/drm/drm-tip
git://anongit.freedesktop.org/drm-tip
https://anongit.freedesktop.org/git/drm/drm-tip
https://anongit.freedesktop.org/git/drm/drm-tip.git
"
drm_tip_repos[drm-xe]="
ssh://git@ssh.gitlab.freedesktop.org/drm/xe/kernel.git
https://gitlab.freedesktop.org/drm/xe/kernel.git
"
drm_old_urls[drm-xe]="
git@gitlab.freedesktop.org:drm/xe/kernel.git
ssh://git@gitlab.freedesktop.org/drm/xe/kernel.git
"
drm_tip_repos[drm-intel]="
ssh://git@ssh.gitlab.freedesktop.org/drm/i915/kernel.git
https://gitlab.freedesktop.org/drm/i915/kernel.git
"
drm_old_urls[drm-intel]="
git@gitlab.freedesktop.org:drm/i915/kernel.git
ssh://git@gitlab.freedesktop.org/drm/i915/kernel.git
ssh://git.freedesktop.org/git/drm/drm-intel
ssh://git.freedesktop.org/git/drm-intel
git://anongit.freedesktop.org/drm/drm-intel
git://anongit.freedesktop.org/drm-intel
https://anongit.freedesktop.org/git/drm/drm-intel
https://anongit.freedesktop.org/git/drm/drm-intel.git
"
drm_tip_repos[drm-misc]="
ssh://git@ssh.gitlab.freedesktop.org/drm/misc/kernel.git
https://gitlab.freedesktop.org/drm/misc/kernel.git
"
drm_old_urls[drm-misc]="
git@gitlab.freedesktop.org:drm/misc/kernel.git
ssh://git@gitlab.freedesktop.org/drm/misc/kernel.git
ssh://git.freedesktop.org/git/drm/drm-misc
ssh://git.freedesktop.org/git/drm-misc
git://anongit.freedesktop.org/drm/drm-misc
git://anongit.freedesktop.org/drm-misc
https://anongit.freedesktop.org/git/drm/drm-misc
https://anongit.freedesktop.org/git/drm/drm-misc.git
"
drm_tip_repos[drm]="
ssh://git@ssh.gitlab.freedesktop.org/drm/kernel.git
https://gitlab.freedesktop.org/drm/kernel.git
"
drm_old_urls[drm]="
git@gitlab.freedesktop.org:drm/kernel.git
ssh://git@gitlab.freedesktop.org/drm/kernel.git
ssh://git.freedesktop.org/git/drm/drm
git://anongit.freedesktop.org/drm/drm
https://anongit.freedesktop.org/git/drm/drm
https://anongit.freedesktop.org/git/drm/drm.git
"
drm_tip_repos[linux-upstream]="
git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
https://kernel.googlesource.com/pub/scm/linux/kernel/git/torvalds/linux.git
"
drm_tip_repos[drm-rust]="
ssh://git@ssh.gitlab.freedesktop.org/drm/rust/kernel.git
https://gitlab.freedesktop.org/drm/rust/kernel.git
"

#
# drm-tip branch configuration array (declared in dim)
#
# Ordered list of branches in repos to merge to the drm-tip integration branch.
#
# Each entry is a string in format: <repo> <branch> [<override-sha1>]
#
# The closing line is used for scripted updates, do not modify.
#
drm_tip_config=(
	"drm			drm-fixes"
	"drm-misc		drm-misc-fixes"
	"drm-rust		drm-rust-fixes"
	"drm-intel		drm-intel-fixes"
	"drm-xe			drm-xe-fixes"

	"drm			drm-next"
	"drm-misc		drm-misc-next-fixes"
	"drm-intel		drm-intel-next-fixes"
	"drm-xe			drm-xe-next-fixes"

	"drm-misc		drm-misc-next"
	"drm-rust		drm-rust-next"
	"drm-intel		drm-intel-next"
	"drm-intel		drm-intel-gt-next"
	"drm-xe			drm-xe-next"

	"drm-intel		topic/core-for-CI"
	"drm-xe			topic/xe-for-CI"
	"drm		topic/drm-next-nouveau-r570"
	"drm-xe		topic/xe-vfio"
	"drm-intel		topic/drm-intel-plane-color-pipeline"
) # DO NOT CHANGE THIS LINE
